
services:
  dmr_master:
    image: dvswitch/testing-hblink3:local
    build:
      context: ../docker/testing/hblink3
    networks:
      - dvswitch_net
    environment:
      DMR_MASTER_PORT: 62031
      DMR_MASTER_PASSWORD: ${BM_PASSWORD:-passw0rd}
    ports:
      - "62031:62031/udp"
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunp | grep -q ':${DMR_MASTER_PORT:-62031}'"]
      interval: 15s
      timeout: 5s
      retries: 20

  mmdvm_bridge:
    image: dvswitch/mmdvm_bridge:local
    build:
      context: ../docker/mmdvm_bridge
    networks:
      - dvswitch_net
    # depends_on:
      # dmr_master:
        # condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.mmdvm_bridge
    # NB: The values below override the .env files, and connect the bridge
    # to the hblink3 DMR master specified above. If you want to connect
    # to another DMR master you can comment out the lines below
    # environment:
      # BM_MASTER_HOST: dmr_master
      # BM_MASTER_PORT: 62031
      # BM_PASSWORD: ${BM_PASSWORD:-passw0rd}
    healthcheck:
      test: ["CMD", "pgrep", "-x", "MMDVM_Bridge"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_bridge:
    image: dvswitch/analog_bridge:local
    build:
      context: ../docker/analog_bridge
    networks:
      - dvswitch_net
    depends_on:
      mmdvm_bridge:
        condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_bridge
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunpt | grep -E ':${USRP_RX_PORT:-32001}|:${USRP_TX_PORT:-32002}'"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_reflector:
    image: dvswitch/analog_reflector:local
    build:
      context: ../docker/analog_reflector
    networks:
      - dvswitch_net
    depends_on:
      analog_bridge:
        condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_reflector
    ports:
      - "12345:12345/tcp"
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunpt | grep -E ':12346'"]
      interval: 15s
      timeout: 5s
      retries: 20

networks:
  dvswitch_net:
    driver: bridge
