
services:
  dmr_master:
    image: dvswitch/testing-hblink3:build-ci
    build:
      context: ../docker/testing/hblink3
    networks:
      - dvswitch_net
    environment:
      DMR_MASTER_PORT: 62031
      DMR_MASTER_PASSWORD: ${BM_PASSWORD:-passw0rd}
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunp | grep -q ':${DMR_MASTER_PORT:-62031}'"]
      interval: 15s
      timeout: 5s
      retries: 20

  mmdvm_bridge:
    image: dvswitch/mmdvm_bridge:build-ci
    build:
      context: ../docker/mmdvm_bridge
    networks:
      - dvswitch_net
    depends_on:
      dmr_master:
        condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.mmdvm_bridge
    environment:
      BM_MASTER_HOST: dmr_master
      BM_MASTER_PORT: 62031
      BM_PASSWORD: ${BM_PASSWORD:-passw0rd}
    healthcheck:
      test: ["CMD", "pgrep", "-x", "MMDVM_Bridge"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_bridge:
    image: dvswitch/analog_bridge:build-ci
    build:
      context: ../docker/analog_bridge
    networks:
      - dvswitch_net
    depends_on:
      mmdvm_bridge:
        condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_bridge
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunpt | grep -E ':${USRP_RX_PORT:-32001}|:${USRP_TX_PORT:-32002}'"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_reflector:
    image: dvswitch/analog_reflector:build-ci
    build:
      context: ../docker/analog_reflector
    networks:
      - dvswitch_net
    depends_on:
      analog_bridge:
        condition: service_healthy
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_reflector
    ports:
      - "12345:12345/tcp"
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost ${MOBILE_PORT:-12345}"]
      interval: 15s
      timeout: 5s
      retries: 20

networks:
  dvswitch_net:
    driver: bridge
