
services:
  mmdvm_bridge:
    image: dvswitch/mmdvm_bridge:build-ci
    build:
      context: ../docker/mmdvm_bridge
    networks: 
      - dvswitch_net
    env_file:
      - ./env/.env.common
      - ./env/.env.mmdvm_bridge
    healthcheck:
      test: ["CMD", "pgrep", "-x", "MMDVM_Bridge"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_bridge:
    image: dvswitch/analog_bridge:build-ci
    build:
      context: ../docker/analog_bridge
    networks: 
      - dvswitch_net
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_bridge
    depends_on:
      mmdvm_bridge:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunpt | grep -E ':${USRP_RX_PORT:-32001}|:${USRP_TX_PORT:-32002}'"]
      interval: 15s
      timeout: 5s
      retries: 20

  analog_reflector:
    image: dvswitch/analog_reflector:build-ci
    build:
      context: ../docker/analog_reflector
    networks: 
      - dvswitch_net
    env_file:
      - ./env/.env.common
      - ./env/.env.analog_reflector
    depends_on:
      analog_bridge:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "ss -lunpt | grep -E ':12346'"]
      interval: 15s
      timeout: 5s
      retries: 20

networks:
  dvswitch_net:
    driver: bridge
