name: CD - Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          short_sha=${GITHUB_SHA::7}
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT
          repo_name_lower=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          echo "repo_name_lower=$repo_name_lower" >> $GITHUB_OUTPUT

      - name: Build and push images (multi-arch)
        run: |
          set -eux
          for comp in mmdvm_bridge analog_bridge analog_reflector; do
            IMAGE="${REGISTRY}/${{ steps.meta.outputs.repo_name_lower }}/${comp}"
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -f docker/${comp}/Dockerfile \
              -t ${IMAGE}:latest \
              -t ${IMAGE}:sha-${{ steps.meta.outputs.short_sha }} \
              --push .
          done

