name: Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  checks: write

env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    needs: unit-tests

  build-and-push:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute tags
        id: meta
        run: |
          short_sha=${GITHUB_SHA::7}
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT
          repo_name_lower=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          echo "repo_name_lower=$repo_name_lower" >> $GITHUB_OUTPUT

      - name: Setup .env files
        run: |
          ./compose/env/setup-env.sh

      - name: Build images
        run: |
          docker compose -f compose/docker-compose.ci.yaml build

      - name: Tag and push images
        run: |
          set -eux
          for comp in mmdvm_bridge analog_bridge analog_reflector; do
            IMAGE="${REGISTRY}/${{ steps.meta.outputs.repo_name_lower }}/${comp}"
            docker tag dvswitch/${comp}:build-ci ${IMAGE}:dev
            docker push ${IMAGE}:dev
          done
