name: Pull request

on:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yaml

  integration-tests:
    uses: ./.github/workflows/integration-tests.yaml
    needs: unit-tests
