name: Unit Tests

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use for testing'
        required: false
        default: '3.11'
        type: string
    outputs:
      test-results:
        description: 'Path to test results'
        value: 'test-results/'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Run unit tests
        run: |
          pytest tests/unit/ -v \
            --tb=short \
            --junitxml=test-results/junit-unit.xml \
            --html=test-results/unit-report.html \
            --self-contained-html

      - name: Unit Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Unit Tests
          path: test-results/junit-unit.xml
          reporter: java-junit
          fail-on-error: false
